--  Warning: This lexical scanner is automatically generated by AFLEX.
--           It is useless to modify it. Change the ".Y" & ".L" files instead.
with Text_IO; use Text_IO;
with mat.expressions.lexer_dfa; use mat.expressions.lexer_dfa; 
with MAT.Expressions.Parser_IO; use MAT.Expressions.Parser_IO; 
--# line 1 "mat-expressions-lexer.l"
--# line 1 "mat-expressions-lexer.l"

with MAT.Types;
with MAT.Expressions;
with MAT.Expressions.Parser_Tokens;
package MAT.Expressions.Lexer is

   use MAT.Expressions.Parser_Tokens;

   function YYLex return Token;

end MAT.Expressions.Lexer;
